networks:            # Docker automatically creates a network, but I choose to do it explicitly so I can give it a name and choose the driver
  pizzageddon-net:
    driver: bridge   # Basically, 'bridge' is a type of virtual network with some rules such as: containers can talk to each other, to the host, to the Internet, 
                     # but the outside world cannot communicate with the containers unless we open their ports
volumes:
  pg-data:
  grafana-data:

services:

  postgres:
    image: postgres:17-alpine      # Latest stable version
    restart: always                # Docker has to attempt to keep running this service no matter what 
    environment:
      POSTGRES_DB: pizzageddon
      POSTGRES_USER: user
      POSTGRES_PASSWORD: chaos2077
    ports:
      - "5432:5432"    # If the main machine receives a request on port 5432, this is going to be redirected automatically to port 5432 of the container instance
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./db/migrations/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./db/migrations/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    networks:
      - pizzageddon-net  # Attach the postgres service to this network 
    healthcheck:         # How Docker makes sure the service is doing is job, and not just running with certain failure
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5


  grafana:
    image: grafana/grafana:11.3.0
    restart: always
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: chaos2077
      GF_USERS_ALLOW_SIGN_UP: false   # Prevent creation of users via the GUI. It's a good practice for security
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - pizzageddon-net
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5


  kitchen:
    build:
      context: .   # This defines the build context for crafting images 
      dockerfile: cmd/kitchen/Dockerfile
    restart: always
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: pizzageddon
      DB_USER: user
      DB_PASSWORD: chaos2077
      GRPC_PORT: 50051
    ports:
      - "50051:50051"
    networks:
      - pizzageddon-net
    depends_on:
      postgres:
        condition: service_healthy


  blitz:
    build:
      context: .
      dockerfile: cmd/blitz/Dockerfile
    environment:
      GRPC_SERVER: kitchen:50051
      ORDERS: ${ORDERS:-1000}
      DURATION: ${DURATION:-60s}
    networks:
      - pizzageddon-net
    depends_on:
      - kitchen
